Issue #3000534 by chr.fritsch: Add a facet select2 widget
thunder/select2 pull request #32
Opened 2018-09-18 10:52 UTC by chrfritsch

2018-10-12 07:51 UTC, chrfritsch commented
@dbosen I need to download search_api and facets on Travis for testing the new sub-module. Is that somehow possible with thunder/travis?

2018-10-16 16:03 UTC, dbosen requested changes

2018-10-16 16:03 UTC, dbosen commented on modules/select2_facets/src/Plugin/facets/widget/Select2Widget.php
> +        $url_object = \Drupal::service('path.validator')->getUrlIfValid($request->getPathInfo());
Please inject services

2018-10-16 16:03 UTC, dbosen commented on modules/select2_facets/src/Plugin/facets/widget/Select2Widget.php
> +      if ($result->getUrl()->isRouted() && $result->getUrl()->getRouteName() === 'facets.block.ajax') {
How can I get into this?

2018-10-16 16:03 UTC, dbosen commented on modules/select2_facets/src/Plugin/facets/widget/Select2Widget.php
> +    $key_value_storage = \Drupal::keyValue('entity_autocomplete');
Another not injected service

2018-10-18 12:18 UTC, dbosen approved these changes

2018-10-18 12:32 UTC, merged