Autocreate values are lost on node preview and autosave resume
thunder/select2 pull request #65
Opened 2019-07-11 13:42 UTC by ol0lll

2019-07-12 10:36 UTC, chrfritsch requested changes
- Doesn't work without autocomplete
- We need tests
- Please move the other fix with a test in a separate issue

2019-07-19 13:42 UTC, ol0lll commented
* Moved getValidReferenceableEntities() to https://github.com/thunder/select2/pull/66
* Added handling for widget without autocomplete but with auto_create

I would prefer another review before writing tests.

2019-07-23 08:56 UTC, chrfritsch commented
Scenario 1:
- Autocreate: On
- Cardinality: Unlimited
- Autocomplete: Off 

The select box only shows already selected entities. Not all existing ones.

Scenario 2:
- Autocreate: On
- Cardinality: 1
- Autocomplete: On 

A newly created entity is gone after the return from the preview

2019-07-25 08:30 UTC, chrfritsch approved these changes

2019-07-25 08:30 UTC, merged